### ISSUE TITLE
Missing answers

### ISSUE THREAD

**Issue by Blinningjr** [Decending/D7020E_lab4#1]
Missing answer for the following questions
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/rtt_timing.rs#L78
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/rtt_timing.rs#L99
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/rtt_timing.rs#L209
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L74
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L130
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L134
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L152
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L159
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L187
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L191
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L231
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L241
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L248
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L258
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L281
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_resources.rs#L291

**Comment by Decending** [comment]
It seems like you've been looking at the wrong branch, the master branch is the one I've turned in.

**Comment by Blinningjr** [comment]
oh, sorry. Didn't notice that you had two branches.

**Comment by Decending** [comment]
No worries, I really should have merged them before. Just take a look at the master branch and review it, I've responded to the other reviewers feedback so there shouldn't be too much to touch on.
