### ISSUE TITLE
Cortex-m4 interrupt latency

### ISSUE THREAD

**Issue by Blinningjr** [Decending/D7020E_lab4#2]
Cortex-m4 has an interrupt latency of about 12 cycles, you can find it in the table here https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/beginner-guide-on-interrupt-latency-and-interrupt-latency-of-the-arm-cortex-m-processors

Update your answer with an explanation as to why RTIC doesn't have any overhead in this case.
https://github.com/Decending/D7020E_lab4/blob/7220e8c323f03e867c0d4e9d5d8ddd98d4a0455e/examples/timing_task.rs#L111

**Comment by Decending** [comment]
This answer has been updated and correctly motivated now.
