### ISSUE TITLE
Review timing_resources

### ISSUE THREAD

**Issue by Blinningjr** [Decending/D7020E_lab4#4]
Your answer to the first question is a bit short, you should mention what the algorithm does and probably also explain what `basepri` is.
https://github.com/Decending/D7020E_lab4/blob/495cb09db22c49be4df349fd076a4bb39d0e5902/examples/timing_resources.rs#L87

I think FreeRTOS requires lock/unlock for shared variables to unsure safe code, thus it requires that the shared variables is locked/unlocked in both functions. So the expression in the link should be multiplied by 2.
https://github.com/Decending/D7020E_lab4/blob/495cb09db22c49be4df349fd076a4bb39d0e5902/examples/timing_resources.rs#L302

Your answer to the last question is a bit short and it is very unclear how removing the need to handle pointer and memory allocation makes it faster.
https://github.com/Decending/D7020E_lab4/blob/495cb09db22c49be4df349fd076a4bb39d0e5902/examples/timing_resources.rs#L323

**Comment by Decending** [comment]
I've now addressed these issues, I'm a bit unsure about the 2nd one regarding shared variables, but I'll try to get a clarification from Per during the lecture today, it is implemented according to the feedback either way.
